### ISSUE TITLE
find assets

### ISSUE THREAD

**Issue by Wholffe** [Wholffe/HexaMath#1]
get or make assets for possible hexagon grids

**Comment by Wholffe** [comment]
found basic hex tiles
https://screamingbrainstudios.itch.io/hex-tiles-toon

**Comment by EricSprunk** [comment]
Nice, looks good. Those are not pointing up as in my imaginations, but I guess that doesn´t matter and this one works better for numbers.

**Comment by Wholffe** [comment]
As placeholders, these should be okay for now. I simply took the first ones that were free, and we will probably replace them with our own designed assets afterward anyway
