### ISSUE TITLE
Integer Limits

### ISSUE THREAD

**Issue by EricSprunk** [Wholffe/HexaMath#3]
Discuss what to do when a player gets a number greater than Integer Range (2^32)

**Comment by Wholffe** [comment]
Since integers in Godot are 64 bits in size, their values range from -2^63 to 2^63 - 1. Although exceeding these limits is likely rare, I would set a threshold x (eg 1e6) to prevent overflow. Goodnight chat

https://docs.godotengine.org/de/4.x/classes/class_int.html

**Comment by Wholffe** [comment]
limit 10e9, -10e9
